// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Username string `json:"username"`
	Secret   string `json:"secret"`
}

type Message struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

type NewUser struct {
	Username string `json:"username"`
	Secret   string `json:"secret"`
}

type Query struct {
}

type User struct {
	ID string `json:"id"`
}
